title: Arduino Organ Console 
description: A site for tracking the progress of converting an old organ console to a MIDI instrument.
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
